### ISSUE TITLE
Document log statements

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#15]
## Concern

The lack of documentation makes some code names really confusing.  Both JS and GO repos have a subset of errors documented in their READMEs, but they don't have things like `EMPTY_PART` or `RCODE_*`, which are part of this test suite.

## Ask

- [ ] Document all log codes in `dnslink-std/test` repo in separate file named  `LOG_CODES.md`
- [ ] Update readmes in GO and JS repos: remove code listings and link to  `LOG_CODES.md` in this repo instead

**Comment by martinheidegger** [comment]
Closed with 
- cc9f7e723ece48443e5d3f875dc5d69a2f3704f8
- https://github.com/dnslink-std/js/commit/c1128c0c7a63eaae3777f67e45381a034c959a5c
- https://github.com/dnslink-std/go/commit/21d712555d21ffe04c96ebbd5f40060c6f1666b3
