### ISSUE TITLE
t04: Repeat _dnslink subdomains  cause  RECURSIVE_DNSLINK_PREFIX entry

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#22]
## Concern

`_dnslink._dnslink.t04.dnslink.example.com` producing `RECURSIVE_DNSLINK_PREFIX`

## Ask

Is this necessary? Feels like an arbitrary choice to mark this as error.  Can we remove this?

 If the goal was to improve UX when someone introduced misconfiguration, then `DUPLICATE_DNSLINK_PREFIX` makes more sense, but I'd rather have us remove this entirely and reduce complexity.

**Comment by martinheidegger** [comment]
What is the fallback strategy for repeat dnslink Subdomains? Should it
fallback until there is no _dnslink. Prefix or should it maximum remove one
dnslink prefix?

**Comment by lidel** [comment]
There should be no special casing – just resolve as you would any other domain name. Added complexity is not worth it.

If someone wants to have DNSLink for `_dnslink.example.com` they should be able to set up TXT record at `_dnslink._dnslink.example.com` and when I open https://dweb.link/ipns/_dnslink.example.com` then it should load the content path published in record at `_dnslink._dnslink.example.com`

**Comment by martinheidegger** [comment]
Just to be clear, for a setup like this:

| Domain | Value |
|---|---|
| a.example.com | A |
| _dnslink.a.example.com | B |
| _dnslink._dnslink.a.example.com | C |
| b.example.com | D |
| _dnslink.b.example.com | E |
| c.example.com | F |

When resolving for `<Query>`:

| Query | Result |
|---|---|
| a.example.com | B |
| _dnslink.a.example.com | B |
| _dnslink._dnslink.a.example.com | C |
| b.example.com | E |
| _dnslink.b.example.com | E |
| _dnslink._dnslink.b.example.com | E |
| c.example.com | F |
| _dnslink.c.example.com | F |
| _dnslink._dnslink.c.example.com | null |

Is that as expected?

**Comment by lidel** [comment]
Results depend if you resolve TXT record on  `_dnslink` and the main domain (both) or only on `_dnslink` (strict).

Resolving (both) introduces performance cost unless you query both in parallel and finish the moment a valid `dnslink=` is received from either of them (discarding the slower/negative one)

Assuming we look up (both) in parallel, i believe it would look like this:

| Query | Result |
|---|---|
| a.example.com | B |
| _dnslink.a.example.com | A or B (whichever is faster and includes dnslink) |
| _dnslink._dnslink.a.example.com | C |
| b.example.com | D or E  (whichever is faster and includes dnslink)   |
| _dnslink.b.example.com | E  |
| _dnslink._dnslink.b.example.com | null (no dnslink on itself and  `_dnslink._dnslink._dnslink.b.example.com` does not exist) |
| c.example.com | F |
| _dnslink.c.example.com | null  (no dnslink on itself or `_dnslink._dnslink.c.example.com`)  |
| _dnslink._dnslink.c.example.com | null  (no dnslink on itself or `_dnslink._dnslink._dnslink.c.example.com`) ||




iirc in go-ipfs we do just that: resolve (both) in parallel and use which arrives first. This is not something we can change, because waiting for both results to arrive would introduce performance regression of initial page loads (sites can have a lot of non-DNSLink TXT records on the main name + TTL passing is broken in go).

---- 

My mental model is that the (both) behavior is specific to IPFS for legacy reasons. 
We support it in libs, but  spec and docs on website informing new deployments should suggest resolving only the `_dnslink`  subdomain. 
Hopefully over time, the majority will use `_dnslink` subdomain and we can drop redundanct lookup for the main one.

**Comment by martinheidegger** [comment]
> iirc in go-ipfs we do just that: resolve (both) in parallel and use which arrives first. 

They indeed resolve them in parallel, but if I don't misunderstand the code  below this wrong: the `_dnslink.` prefix gets precedence, making it deterministic.

https://github.com/ipfs/go-namesys/blob/434a74d16f305355ca3113dcfa93b8bbf68ea49e/dns.go#L107-L108

How do you think about adding a warning to the log when not using a `_dnslink.` prefixed domain to alert people who specify things without a `_dnslink.` prefix about the deprecation?

**Comment by lidel** [comment]
- Good catch with the determinism in namesys – I misremembered.
  Yes, we should do the same (wait for `_dnslink` if main domain resolved first, and prefer value from `_dnslink` if both are present). 
- Adding deprecation warning is a very good idea! :+1:  It should be very prominent on website – similar to yellow one when record is invalid or missing – filled https://github.com/dnslink-std/dnslink-website/issues/20 so we don't forget.

**Comment by martinheidegger** [comment]
Closed by 4c6ffdc8624d75055ec43e72799059a1319ee0ac
