### ISSUE TITLE
t06: rename test and remove trimming

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#23]
## Concern

- confusing description
- trimming is absolute no – DNSLink should not mutate content paths in any way.

## Ask 

- rename it to "Multiple valid entries for the same key should be returned in alphabetical order"
- remove trimming operation from tests and libraries and have tests that confirm whitespace characters are not trimmed

**Comment by martinheidegger** [comment]
Closed with e805feaf16a9e13e59ceafca056dbb8ca451505b
