### ISSUE TITLE
t11 & t12: reuse TOO_MANY_REDIRECTS for ENDLESS_REDIRECT ?

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#25]
## Concern 

Any reason why we can't reuse `TOO_MANY_REDIRECTS` for `ENDLESS_REDIRECT` edge case?
This is essentially the same error and collapsing this simplifies implementations and error handling in userland.

## Ask

remove ENDLESS_REDIRECT, reuse  TOO_MANY_REDIRECTS for handling infinite loop

**Comment by martinheidegger** [comment]
As i understand  #16, redirects should be gone anyways and with that also those cases.

**Comment by lidel** [comment]
Ah, yes!

**Comment by martinheidegger** [comment]
Closed with #16
