### ISSUE TITLE
Remove unnecessary DNS validation ( t17, t19, t20)

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#26]
## Concern

Tests like  t17, t19, t20 are mixing concerns and responsibilities: it is not our job to do DNS record validation, this adds unnecessary complexity that implementers need to do to be "compliant" 

## Ask

Temove this type of DNS validation, leave it up to DNS resolver to return an error

**Comment by martinheidegger** [comment]
Part of #16

**Comment by martinheidegger** [comment]
Closed with #16
