### ISSUE TITLE
t18: rename RCODE_N to DNS_RCODE_N

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#27]
nit: rename RCODE_N to DNS_RCODE_N to indicate that code comes from DNS system itself

**Comment by martinheidegger** [comment]
Closed with
- 46b051f2459709fac09210c4db10a8062a3e16b1
- https://github.com/dnslink-std/go/commit/54bec4c859e828d0a71595f404e8fd929dd39c98
- https://github.com/dnslink-std/js/commit/1ab3fca2cbab29281f5a95dd66836c133b840f70
