### ISSUE TITLE
CLI behavior (test/js/go): fix domains used in --help texts

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#29]
### Concern

CLI tools have `--help` which includes examples of  real or non-existent domains. 
Some examples from .dnslink.dev are broken and do not resolve, which is a bad UX.

## Ask

- Switch `--help` texts to use `*.dnslink.example.com` (https://github.com/dnslink-std/test/issues/12)  so it is clear to user that they should not expect them to work 
- Always include link to https://dnslink.dev for "more docs and examples"

**Comment by martinheidegger** [comment]
Both CLI's now contain working domains and a link to dnslink.dev
