### ISSUE TITLE
CLI behavior (test/js/go): full form parameters in examples

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#30]
nit: use full form parameters in `--help` examples (eg. `—format=json` instead of `-f=json`) so reader does need to jump up and down to know what each one does

**Comment by martinheidegger** [comment]
Fixed with:
- https://github.com/dnslink-std/js/commit/e543361690da714b21106055427a721b32502adb
- https://github.com/dnslink-std/go/commit/4e9a49606a666a96ddda2df1026de52ed09a8142
