### ISSUE TITLE
TTL behavior in CLI (test/js/go)

### ISSUE THREAD

**Issue by lidel** [dnslink-std/test#31]
## Concern

TTL is noise unless user cares about it and wants to use it for cache-control.

## Ask

- Default CLI output should not have TTL.   (look like current `-f=reduced`)
- Add opt-in  `--ttl` parameter to include it in text output.

**Comment by martinheidegger** [comment]
Wouldn't it be a better idea to remove the `reduced` mode and remove the `ttl` from the display? If someone needs the ttl: `json` and `csv` still provide it.

**Comment by martinheidegger** [comment]
Closed with:

- https://github.com/dnslink-std/js/commit/995bfe356416b6c666b5c6274871820d6f55ee22
- https://github.com/dnslink-std/go/commit/0527eac64b6bb03ca0184c4f25e369445dab5633
