### ISSUE TITLE
Add Test for unqualified domain

### ISSUE THREAD

**Issue by martinheidegger** [dnslink-std/test#5]
Another common behavior is how to act with a unqualified domain (i.e.: "google")

**Comment by lidel** [comment]
Yes,  `foobar.` is a valid FQDN, one level under the DNS root (implicit `.`). 
Users should be able to use top level names like this (either by running own DNS or something like https://handshake.org/)

**Comment by martinheidegger** [comment]
Added a bunch of fqdn test in f36bb2440c863cc4d0f648f55c83517025f4f0f9 and an explicit `.` suffix test in 7e1543c31ccfb6d778d91185cc023c1a4486558b
