### ISSUE TITLE
Add test for combined TXT settings

### ISSUE THREAD

**Issue by martinheidegger** [dnslink-std/test#8]
When implementing DNSLink for golang, I noticed that golang's dnsResolver [combines multiple returned TXT entries](https://github.com/golang/go/commit/a6df1cece7f6b62a1e1b09f9027692ac0d5411a1) making it necessary to adjust the DNS output for that case: https://github.com/dnslink-std/test/commit/661a2ec3076247bb05461562a95af2a49892dc87 Obviously this is different between the implementations. My current belief, after reading the golang issue, is that they made a mistand and having them separate is the correct way to go about, but in any case there should be a test whether or not an implementation supports multiple dns entries or not. That test needs to be optional or there needs to be a switch that tests either/or.

**Comment by martinheidegger** [comment]
Note: `go-doh-resolver` seems to [also provide each txt statement as array instead of combined](https://github.com/libp2p/go-doh-resolver/blob/4571ac1633ada52ec93723fc84fc3ee6381cfbb7/request.go#L138).

> `v.Txt...`

**Comment by lidel** [comment]
Interesting. iiuc they concatenate strings  only when a single DNS TXT record has more than one string.

I believe the confusion here comes from the fact that that a  [TXT record](https://en.wikipedia.org/wiki/TXT_record) can have more than one string:
1. a domain may have multiple TXT records associated with it
2. each record can in turn have one or more character strings

Concatenation introduced in  https://github.com/golang/go/commit/a6df1cece7f6b62a1e1b09f9027692ac0d5411a1 occurs for (2) 
and [what go-doh-resolver  does](https://github.com/libp2p/go-doh-resolver/blob/4571ac1633ada52ec93723fc84fc3ee6381cfbb7/request.go#L138) is appending records, so it  operates on (1) – different abstraction layers.


I think DNS libs return full records, hiding the string concatenation within a single record as internal implementation detail. If that is true, then dnslink library should do/expect  the same.

**Comment by martinheidegger** [comment]
Agreed. The current implementations respect this equally. The recent test for the `253` character limit required the use of multiple strings per TXT record to be concatenated. https://github.com/dnslink-std/test/blob/f50fa13326ef81eb3f9753e2876d5149b01ebbd6/integration-tests.js#L494
