### ISSUE TITLE
Add /dnslink/ instead of /dns/

### ISSUE THREAD

**Issue by martinheidegger** [dnslink-std/test#9]
Technically the `/dns/` is an implementation _mistake_ by the `go-dnslink` module, while the documentation on https://dnslink.dev points to `/dnslink/`. To be backwards compatible the libraries should support `/dnslink/` as well as `/dns/` with preference for `/dnslink/`.

**Comment by lidel** [comment]
I don't remember seeing `/dns` being used anywhere in real world (recursive dnslinks in IPFS ecosystem all use  `/ipns/`)
I suggest we only support `/dnslink` in the new libs, as we effectively introduce it for the first time. Until now, it was just theoretical.
